pub mod monitor;
pub mod fanotify;
pub mod netlink;
pub mod process_monitor;
pub mod enhanced_monitor;
pub mod network_filter;
pub mod iptables;
pub mod patterns;
pub mod netfilter;
pub mod dns_filter;
pub mod event_correlation;

pub use monitor::LinuxSecurityMonitor;
pub use fanotify::FanotifyMonitor;
pub use netlink::NetlinkMonitor;
pub use process_monitor::ProcessMonitor;
pub use enhanced_monitor::{EnhancedSecurityMonitor, SecurityPolicy, EnforcementMode};
pub use network_filter::{NetworkFilter, NetworkFilterRule, NetworkEvent, FilterAction, Direction, Protocol};
pub use iptables::{IptablesManager, IptablesRule, Chain, RuleAction};
pub use patterns::{PatternMatcher, BehaviorPattern, PatternCategory, Severity, ProcessChain};
pub use netfilter::{NetfilterManager, NetfilterRule, NftRule};
pub use dns_filter::{DnsFilter, DnsFilterConfig, DnsEvent, DnsAction};
pub use event_correlation::{EventCorrelator, CorrelationRule, CorrelatedEvent};